Not Found: /deportistas/2/reportew
"GET /deportistas/2/reportew HTTP/1.1" 404 1730
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 1728
Not Found: /deportistas/2/reportew
"GET /deportistas/2/reportew HTTP/1.1" 404 179
Not Found: /deportistas/2/reportew
"GET /deportistas/2/reportew HTTP/1.1" 404 179
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 179
Internal Server Error: /deportistas/2/reporte
Traceback (most recent call last):
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/loader_tags.py", line 197, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/engine.py", line 212, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: navbar.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/backends/django.py", line 64, in render
    reraise(exc, self.backend)
  File "/Volumes/PRIMERPLANO/toshiba DD/apps/dinametrics/.env/lib/python3.11/site-packages/django/template/backends/django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: navbar.html
"GET /deportistas/2/reporte HTTP/1.1" 500 145
